[package]
name = "shooter3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true


[dependencies]
sdl2 = "0.35"
nalgebra = "0.32.2"
